project:
  type: book

book:
  title: "PTOS-open-data"
  author: "Jürgen Schneider"
  date: "16.11.2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  page-navigation: true

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



