# Workflow 1


## Search for reusable data

**Why?**  
For resource intensive data collections this could save you a lot of time and money  
   
**Resources**  
Research data centers have searchable databases

* [re3data.org](https://www.re3data.org/) (Database to search for databases)
* [Verbund FDB](https://www.forschungsdaten-bildung.de/) (Education)
* [RDC at ZPID](https://rdc-psychology.org/) (Psychology)

\


## Decide between sharing for reuse or reproducibility

**Why?**  

* Providing data at a reseach data center costs time and money for you and the data center
* Typically, 
  - sharing for reuse purposes is suited for research data centers
  - sharing for reproducibility purposes is suited for repositories
   
**Resources**  
I am not aware of any standards to make this decision. Here are a couple of guidelines to decide, if your data is fit for reuse

* Costs:
  - How much effort is required for well-documented data sharing (e.g., Does a codebook exist? What steps are necessary for data cleaning/editing?)
  - Is there consent for reuse available or would it have to be obtained retrospectively?
* Benefits:
  - Analysis potential (e.g., not fully analyzed, type of data, connected with other data sources)
  - Quality of data (e.g., representative, size, special features of sample)

::: {.column-margin}
Questions to be answered at the end?  
Please [put them here](https://cryptpad.fr/pad/#/2/pad/edit/cuCPFUjVKcURc7JZSKt57dK2/embed/)!
:::

\